apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: redis
    component: cache
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
        component: cache
    spec:
      containers:
      - name: redis
        image: k8s.gcr.io/redis:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
          name: redis
        env:
        - name: MASTER
          value: "true"
